services:
  sherlock:
    container_name: sherlock
    build:
      context: .
      dockerfile: Dockerfile
    image: michaelwenk/sherlock
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - sherlock-db-mongo
      - sherlock-db-postgres
    environment:
      - VERSION=${VERSION}
      - CONTEXT_PATH=${CONTEXT_PATH}
      # - PORT=${PORT}
      # - HOSTNAME=${HOSTNAME}
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
      - SHERLOCK_CORS_ALLOWED_ORIGIN_PATTERNS=${SHERLOCK_CORS_ALLOWED_ORIGIN_PATTERNS}

  sherlock-db-mongo:
    container_name: sherlock-db-mongo
    image: mongo:8
    ports:
      - "8081:27017"
    # command:
    #   --wiredTigerCacheSizeGB 4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./data/db-mongo:/data/db"

  sherlock-db-postgres:
    container_name: sherlock-db-postgres
    image: postgres:18
    command:
      - "postgres"
      - "-c"
      - "max_wal_size=8GB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "checkpoint_timeout=30min"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
    volumes:
      - "./data/db-postgres/:/var/lib/postgresql"      
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fragment
    ports:
      - "8082:5432"