services:
  sherlock:
    container_name: sherlock
    build:
      context: .
      dockerfile: Dockerfile
    image: michaelwenk/sherlock
    ports:
      - "8080:8080"
    depends_on:
      - sherlock-db-mongo
      - sherlock-db-postgres

  sherlock-db-mongo:
    container_name: sherlock-db-mongo
    image: mongo:8
    ports:
      - "8081:27017"
    # command:
    #   --wiredTigerCacheSizeGB 4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "./data/db-mongo:/data/db"

  sherlock-db-postgres:
    container_name: sherlock-db-postgres
    image: postgres:18
    volumes:
      - "./data/db-postgres/:/var/lib/postgresql"      
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fragment
    ports:
      - "8082:5432"