spring.application.name=sherlock
server.servlet.context-path=${CONTEXT_PATH:/}
# server.port=${PORT:8080}
# server.address=${HOSTNAME:localhost}

### dbservice 
## dataset
# mongodb
mongodb.dataset.uri=mongodb://admin:password@sherlock-db-mongo:27017/dataset?authSource=admin
# postgres
spring.datasource.url=jdbc:postgresql://sherlock-db-postgres:5432/fragment
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.show-sql=false
# hibernate
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.sql=warn
logging.level.org.openscience.sherlock.dbservice.statistics.controller.HOSECodeController=DEBUG

## result
# mongodb
mongodb.result.uri=mongodb://admin:password@sherlock-db-mongo:27017/result?authSource=admin
# default Spring Mongo URI (used by Boot auto-configured beans)
spring.mongodb.uri=${mongodb.result.uri}

## statistics 
# mongodb
mongodb.statistics.uri=mongodb://admin:password@sherlock-db-mongo:27017/statistics?authSource=admin

### job scheduler
sherlock.job.pool-size=4
sherlock.job.queue-size=1000

### statistics
sherlock.statistics.hosecode.replace-all-batch-size=250

# Sherlock
sherlock.version=${VERSION:N/A}


# OpenAPI
springdoc.api-docs.path=/api-docs
# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# security 
spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:password}
sherlock.cors.allowed-origin-patterns=${SHERLOCK_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*}
